
spring:
  profiles: it
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: ${DB_URL:jdbc:h2:mem:apptmngr;DB_CLOSE_ON_EXIT=TRUE;MODE=MYSQL}
    username: sa
    password:
    driver-class: org.h2.Driver
    jpa:
      show-sql: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
